apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-package-build
  namespace: base-repo-ci
spec:
  params:
  - name: package-for-build
    description: Package name for build
    type: string
  - name: http_proxy
    description: http_proxy for container and mock
    type: string
  - name: https_proxy
    description: https_proxy for container and mock
    type: string
  - name: no_proxy
    description: no_proxy for container and mock
    type: string
  - name: registry
    description: container registry prefix
    type: string
  resources:
    inputs:
    - name: source
      type: git
  workspaces:
    - name: output
  steps:
  - name: pre-build-check
    image: $(params.registry)/il-package-builder
    env:
      - name: "http_proxy"
        value: $(params.http_proxy)
      - name: "https_proxy"
        value: $(params.https_proxy)
      - name: "no_proxy"
        value: $(params.no_proxy)
    script: |
      #! /bin/bash
      echo "=> Build Package  : $(params.package-for-build) ..."
      echo "   http_proxy     : $(params.http_proxy)"
      echo "   https_proxy    : $(params.https_proxy)"
      echo "   no_proxy       : $(params.no_proxy)"
      echo "   registry       : $(params.registry)"
      echo "   output path    : $(workspaces.output.path)"
      echo ""
      echo "   Source Path: $(inputs.resources.source.path)"
      echo "   Git URL    : $(inputs.resources.source.url)"
      echo "   Git Version: $(inputs.resources.source.revision)"
      echo "   Git refspec: $(inputs.resources.source.refspec)"
      echo ""
      echo "=> /etc/mock/site-defaults.cfg"
      cat /etc/mock/site-defaults.cfg
      echo ""
      echo "=> /etc/mock/intel-linux-centos.cfg"
      cat /etc/mock/intel-linux-centos.cfg
  - name: mock-build
    image: $(params.registry)/il-package-builder
    env:
    - name: "PACKAGE"
      value: "$(params.package-for-build)"
    - name: "http_proxy"
      value: $(params.http_proxy)
    - name: "https_proxy"
      value: $(params.https_proxy)
    - name: "no_proxy"
      value: $(params.no_proxy)
    command:
      - /usr/bin/mock-build.sh
    securityContext:
      runAsUser: 0
      privileged: true        
    volumeMounts:
    - name: cache
      mountPath: /opt/cache
    - name: build
      mountPath: /workspace/build
  - name: publish
    image: alpine:3.11
    script: |
      #! /bin/sh
      ls /workspace/build/$(params.package-for-build)
      cp /workspace/build/$(params.package-for-build)/result/*.rpm $(workspaces.output.path)
      chmod 777 $(workspaces.output.path)
      ls $(workspaces.output.path)
    volumeMounts:
    - name: build
      mountPath: /workspace/build
  volumes:
  - name: cache
    emptyDir: {}
  - name: build
    emptyDir: {}
