apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-publish-base-repo
spec:
  workspaces:
  - name: base-repo-dir
  params:
  - name: registry
  steps:
  - name: createrepo
    image: $(params.registry)/il-package-builder
    script: |
      #! /bin/bash
      ls $(workspaces.base-repo-dir.path)
      echo "--"
      cd $(workspaces.base-repo-dir.path)
      createrepo .
      echo "--"
      ls $(workspaces.base-repo-dir.path)
