apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: review-pipeline-binding
spec:
  params:
  - name: gitrevision
    value: $(body.pull_request.head.sha)
  - name: gitrepositoryurl
    value: $(body.pull_request.head.repo.clone_url)
  - name: prurl
    value: $(body.pull_request.html_url)
  - name: repo
    value: $(body.pull_request.base.repo.full_name)
  - name: action
    value: $(body.action)
  - name: source
    value: github
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-full-test-on-pull-request
spec:
  params:
  - name: action
    type: string
  inputs:
    resources:
    - name: repo
      type: git
    - name: pr
      type: pullRequest
  outputs:
    resources:
    - name: pr
      type: pullRequest
  steps:
  - name: set
    image: ubuntu
    command: ["/bin/bash"]
    args:
    - -ce
    - |
        set -e
        echo "action       : $(params.action)"
        echo "git repo url : $(inputs.resources.repo.url)"
        echo "git revision : $(inputs.resources.repo.revision)"
        echo "pr url       : $(inputs.resources.pr.url)"
        echo ""

        cat /workspace/pr/pr.json

        # Get the PR number from the PR URL.
        prurl="$(inputs.resources.pr.url)"
        prNum=$(echo "$prurl" | awk -F/ '{print $NF}')

        echo ""

        cp -r /workspace/pr/ /workspace/output/
        if [[ "$(params.action)" =~ ^(reopened|opened) ]]; then
          echo "PR URL: $prurl"
          echo "PR Number: $prNum"
          echo "Thanks for your PR, this is Tekton Robot!" > /workspace/output/pr/comments/new
        else
          echo "Unknown action: $(params.action)"
        fi
---
apiVersion: v1
kind: Secret
metadata:
  name: il-github-pr-token
type: Opaque
stringData:
  token: "f21177445edd98d05e50b2888ed752e1b204a97f"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: review-pipeline-template
spec:
  params:
  - name: gitrevision
    default: master
  - name: gitrepositoryurl
  - name: prurl
  - name: repo
  - name: action
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
        - name: httpProxy
          value: "http://192.168.0.4:8118"
        - name: httpsProxy
          value: "http://192.168.0.4:8118"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: pr-$(uid)
      spec:
        type: pullRequest
        params:
        - name: url
          value: $(params.prurl)
        secrets:
        - secretName: il-github-pr-token
          secretKey: token
          fieldName: authToken
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun
      metadata:
        generateName: run-full-test-on-pull-request-
      spec:
        taskRef:
          name: run-full-test-on-pull-request
        params:
        - name: action
          value: $(params.action)
        inputs:
          resources:
            - name: repo
              resourceRef:
                name: git-source-$(uid)
            - name: pr
              resourceRef:
                name: pr-$(uid)
        outputs:
          resources:
            - name: pr
              resourceRef:
                name: pr-$(uid)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: il-github-pr
spec:
  serviceType: NodePort
  serviceAccountName: il-tekton-ci-sa
  triggers:
    - name: pr-trig
      interceptors:
        - github:
            eventTypes: 
              - pull_request
      bindings:
        - name: review-pipeline-binding
      template:
        name: review-pipeline-template