apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: review-pipeline-binding
spec:
  params:
  - name: gitrevision
    value: $(body.pull_request.head.sha)
  - name: gitrepositoryurl
    value: $(body.pull_request.head.repo.clone_url)
  - name: prurl
    value: $(body.pull_request.html_url)
  - name: repo
    value: $(body.pull_request.base.repo.full_name)
  - name: action
    value: $(body.action)
  - name: source
    value: github
---
apiVersion: v1
kind: Secret
metadata:
  name: il-github-pr-token
type: Opaque
stringData:
  token: "0c1c8b53cdd43516002e24b1de2bf43b6f432baa"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: review-pipeline-template
spec:
  params:
  - name: gitrevision
    default: master
  - name: gitrepositoryurl
  - name: prurl
  - name: repo
  - name: action
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
        - name: httpProxy
          value: "http://192.168.0.4:8118"
        - name: httpsProxy
          value: "http://192.168.0.4:8118"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: pr-$(uid)
      spec:
        type: pullRequest
        params:
        - name: url
          value: $(params.prurl)
        secrets:
        - secretName: il-github-pr-token
          secretKey: token
          fieldName: authToken
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: run-pipeline-verify-pr-
      spec:
        pipelineRef:
          name: pipeline-verify-pr
        params:
        - name: http_proxy
          value: "http://192.168.0.4:8118"
        - name: https_proxy
          value: "http://192.168.0.4:8118"
        - name: no_proxy
          value: 127.0.0.1,localhost,192.168.0.6
        - name: registry
          value: bluewish
        - name: pr-action
          value: $(params.action)
        resources:
        - name: centorepo-git
          resourceRef:
            name: git-source-$(uid)
        - name: pr-for-verify
          resourceRef:
            name: pr-$(uid)
        workspaces:
        - name: output_repo
          emptyDir: {}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: il-github-pr
spec:
  serviceType: NodePort
  serviceAccountName: il-tekton-ci-sa
  triggers:
    - name: pr-trig
      interceptors:
        - github:
            eventTypes: 
              - pull_request
      bindings:
        - name: review-pipeline-binding
      template:
        name: review-pipeline-template