apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: il-github-echo-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun
      metadata:
        generateName: il-github-run-
      spec:
        taskSpec:
          inputs:
            resources:
              - name: source
                type: git
          steps:
            - image: ubuntu
              script: |
                #! /bin/bash
                ls -al $(inputs.resources.source.path)
        inputs:
          resources:
            - name: source
              resourceSpec:
                type: git
                params:
                  - name: revision
                    value: $(params.gitrevision)
                  - name: url
                    value: $(params.gitrepositoryurl)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: il-github-push-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: docker-tag
    value: $(body.repository.name):$(body.head_commit.id)
  - name: event-type
    value: $(header.X-Github-Event)
---
apiVersion: v1
kind: Secret
metadata:
  name: il-github-secret
type: Opaque
stringData:
  githubToken: 123intel
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: il-github-listener
spec:
  # from examples/role-resources/servicaccount.yaml
  serviceAccountName: il-tekton-ci-sa
  triggers:
    - name: il-github-push-events-trigger
      interceptors:
        - github:
            eventTypes: ["push"]  # Only push events
      bindings:
        - name: il-github-push-binding
      template:
        name: il-github-echo-template
  serviceType: NodePort
