apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: repo-master-git
  namespace: default
spec:
  type: git
  params:
  - name: url
    value: https://github.com/kenplusplus/centos-repo
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-package-build
spec:
  params:
  - name: package-for-build
    description: Package name for build
    type: string
  - name: http_proxy
    type: string
  - name: https_proxy
    type: string
  - name: no_proxy
    type: string
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - name: pre-build-check
    image: 192.168.0.6:83/il-ci/il-package-builder
    env:
      - name: "http_proxy"
        value: $(params.http_proxy)
      - name: "https_proxy"
        value: $(https_proxy)
      - name: "no_proxy"
        value: $(params.no_proxy)
    script: |
      #! /bin/bash
      echo $(inputs.resources.source.path)
      ls -al $(inputs.resources.source.path)
      echo ">> proxy setting"
      echo $http_proxy
      echo $no_proxy
      echo "package for build: $(params.package-for-build)"
  - name: mock-build
    image: 192.168.0.6:83/il-ci/il-package-builder
    env:
    - name: "PACKAGE"
      value: "$(params.package-for-build)"
    - name: "http_proxy"
      value: $(params.http_proxy)
    - name: "https_proxy"
      value: $(https_proxy)
    - name: "no_proxy"
      value: $(params.no_proxy)
    command:
      - /usr/bin/mock-build.sh
    securityContext:
      runAsUser: 0
      privileged: true        
    volumeMounts:
    - name: cache
      mountPath: /opt/cache
    - name: buildroot
      mountPath: /workspace/build
  volumes:
  - name: cache
    emptyDir: {}
  - name: buildroot
    emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-all-packages
spec:
  resources:
  - name: centorepo-git
    type: git
  params:
  - name: http_proxy
    default: "http://192.168.0.4:8118"
  - name: https_proxy
    default: "https://192.168.0.4:8118"
  - name: no_proxy
    default: 127.0.0.1,localhost,192.168.0.6
  tasks:
  - name: build-linux-sgx-driver
    taskRef:
      name: task-package-build
    resources:
      inputs:
      - name: source
        resource: centorepo-git
    params:
    - name: package-for-build
      value: linux-sgx-driver
    - name: http_proxy
      value: $(params.http_proxy)
    - name: https_proxy
      value: $(params.https_proxy)
    - name: no_proxy
      value: $(params.no_proxy)
  - name: build-linux-sgx-sdk
    taskRef:
      name: task-package-build
    resources:
      inputs:
      - name: source
        resource: centorepo-git
    params:
    - name: package-for-build
      value: linux-sgx-sdk
    - name: http_proxy
      value: $(params.http_proxy)
    - name: https_proxy
      value: $(params.https_proxy)
    - name: no_proxy
      value: $(params.no_proxy)
  - name: build-glibc-intel-avx
    taskRef:
      name: task-package-build
    resources:
      inputs:
      - name: source
        resource: centorepo-git
    params:
    - name: package-for-build
      value: glibc-intel-avx
    - name: http_proxy
      value: $(params.http_proxy)
    - name: https_proxy
      value: $(params.https_proxy)
    - name: no_proxy
      value: $(params.no_proxy)
  - name: build-phoronix-test-suite
    taskRef:
      name: task-package-build
    resources:
      inputs:
      - name: source
        resource: centorepo-git
    params:
    - name: package-for-build
      value: phoronix-test-suite
    - name: http_proxy
      value: $(params.http_proxy)
    - name: https_proxy
      value: $(params.https_proxy)
    - name: no_proxy
      value: $(params.no_proxy)
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-build-all-packages
spec:
  pipelineRef:
    name: pipeline-build-all-packages
  resources:
  - name: centorepo-git
    resourceRef:
      name: repo-master-git