apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-package-build
spec:
  params:
    - name: package-for-build
      description: Package name for build
      type: string
    - name: http_proxy
      type: string
    - name: https_proxy
      type: string
    - name: no_proxy
      type: string
  resources:
    inputs:
    - name: source
      type: git
  steps:
    - name: pre-build-check
      image: 192.168.0.6:83/il-ci/il-package-builder
      env:
        - name: "http_proxy"
          value: $(params.http_proxy)
        - name: "https_proxy"
          value: $(https_proxy)
        - name: "no_proxy"
          value: $(params.no_proxy)
      script: |
        #! /bin/bash
        echo $(inputs.resources.source.path)
        ls -al $(inputs.resources.source.path)
        echo ">> proxy setting"
        echo $http_proxy
        echo $no_proxy
        echo "package for build: $package-for-build"
    - name: mock-build
      image: 192.168.0.6:83/il-ci/il-package-builder
      env:
      - name: "PACKAGE"
        value: "$(params.package-for-build)"
      - name: "http_proxy"
        value: $(params.http_proxy)
      - name: "https_proxy"
        value: $(https_proxy)
      - name: "no_proxy"
        value: $(params.no_proxy)
      command:
        - /usr/bin/mock-build.sh
      securityContext:
        runAsUser: 0
        privileged: true        
      volumeMounts:
        - name: cache
          mountPath: /opt/cache
        - name: buildroot
          mountPath: /workspace/build
  volumes:
    - name: cache
      emptyDir: {}
    - name: buildroot
      emptyDir: {}
