apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: repo-master-git
  namespace: default
spec:
  type: git
  params:
  - name: url
    value: https://github.com/kenplusplus/centos-repo
  - name: revision
    value: master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-repo-dir
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-build-all-packages
spec:
  pipelineRef:
    name: pipeline-build-all-packages
  workspaces:  
  - name: output_repo
    persistentVolumeClaim:
      claimName: base-repo-dir
  resources:
  - name: centorepo-git
    resourceRef:
      name: repo-master-git
  params:
    - name: http_proxy
      value: ""
    - name: https_proxy
      value: ""
    - name: no_proxy
      value: "127.0.0.1,localhost,192.168.0.6"
    - name: registry
      value: "bluewish"
