apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: repo-master-git
  namespace: base-repo-ci
spec:
  type: git
  params:
  - name: url
    value: https://github.com/kenplusplus/centos-repo
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-build-all-packages
  namespace: base-repo-ci
spec:
  pipelineRef:
    name: pipeline-build-all-packages
  workspaces:
  - name: output_repo
    persistentVolumeClaim:
      claimName: centos-base-repo-dir-pvc
  resources:
  - name: centorepo-git
    resourceRef:
      name: repo-master-git
  params:
    - name: http_proxy
      value: ""
    - name: https_proxy
      value: ""
    - name: no_proxy
      value: ""
    - name: registry
      value: "192.168.0.6:83/bluewish"
