apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: taskrun-build-package-
spec:
  taskRef:
    name: task-package-build
  resources:
    inputs:
    - name: source
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.intel.com/intel-base-linux-repo/centos-repo.git
  params:
    - name: package-for-build
      value: linux-sgx-sdk
    - name: http_proxy
      value: "http://child-prc.intel.com:913"
    - name: https_proxy
      value: "https://child-prc.intel.com:913"
    - name: no_proxy
      value: "127.0.0.1,localhost,.intel.com"
    - name: registry
      value: "il-prc-pub.sh.intel.com:31007/baserepo"
