apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: taskrun-build-package-
spec:
  taskRef:
    name: task-package-build
  resources:
    inputs:
    - name: source
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/kenplusplus/centos-repo
  params:
    - name: package-for-build
      value: linux-sgx-sdk
    - name: http_proxy
      value: "http://192.168.0.4:8118"
    - name: https_proxy
      value: "https://192.168.0.4:8118"
    - name: no_proxy
      value: "127.0.0.1,localhost,192.168.0.6"
    - name: registry
      value: "bluewish"
